name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        default: "false"
        required: false
      logLevel:
        description: Log Level
        default: debug
        required: false

jobs:
  ci-pipeline:
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: read
    runs-on: runner-homeops
    steps:
  
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build Images
        run: |
          docker compose build

